# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42f11d325a20649b51c7990529c08c5571e8aba064b3b1771e0708efae42397c9d8ac17ad9a408cbb728017851f3aded25608434870c460df9af357b0a028238

test:
  secret_key_base: 7bf390a940587779a623f92e7d1af0587695136ad2ae6ef17bc7286c15920ac8f693b4186d2cd1ef8a9a2e53d6865cff9c7de87e60e765cb217f375ea95636df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
